config:
  image_grid_width_sm: 640
  image_grid_width_md: 1080
  image_grid_width_lg: 1800
  image_width_sm: 1080
  image_width_md: 1800
  image_width_lg: 2400
  font_stack_system: >-
    -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu,
    Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"
metadata:
  site_url: 'https://main--preeminent-bublanina-94c1b4.netlify.app/'
  site_title: Nathaniel Miller Architecture
  site_subtitle_1: null
  site_subtitle_2: null
  site_description: >
    NMA is a new, minimalist, architecutural studio for residential
    connoisseurs.


    Contact us here: email
  site_email: bo0yswbrp@mozmail.com
  site_social_url: 'https://nz.linkedin.com/in/nat-miller-46648b86'
  site_icon_svg: /assets/uploads/favicon.svg
  site_icon_png: /assets/uploads/favicon.png
  site_ga4_id: ''
  seo:
    site_title: NMA - noice architecture
    site_description: >-
      Nathaniel Miller Architecture is a dynamic, minimalist, architecutural
      studio for residential connoisseurs
    no_index: false
theme:
  theme_layout:
    space_scale: 100
  theme_colors:
    background: '#ffffff'
    text: '#101010'
    link: '#101010'
    background_dark: '#101010'
    text_dark: '#c1c1c1'
    link_dark: '#ffffff'
  theme_typography:
    font: Cairo
    font_weight: 200
    font_scale: 100
    line_height_scale: 100
  theme_features:
    enable_dark_mode: false
    item_output_limit: 48
    transition_duration: 300
    show_project_year: true
    show_project_grid_titles: true
images:
  avif:
    enabled: true
    quality: 75
  webp:
    enabled: true
    quality: 75
  jpeg:
    enabled: true
    quality: 75
i18n:
  site_language: en
  site_social_title: LinkedIn
